name: "Generate the EBML RFC"
# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master, rfc8794 ]
  pull_request:

jobs:
  build:
    name: "Build RFCS"
    runs-on: ubuntu-22.04
    steps:
      - name: Get pushed code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get python (for xml2rfc)
        uses: actions/setup-python@v4

      - name: Setup toolchain
        run: ./bootstrap

      - name: Build
        run: make

      - name: XML Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ebml-ietf-xmls
          path: |
            rfc8794.xml
            draft-ietf-cellar-ebml-*.xml
