name: "Generate the EBML RFC"
# Trigger the workflow on push or pull request
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: "Build RFCS"
    runs-on: ubuntu-22.04
    steps:
      - name: Get pushed code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Get python (for xml2rfc)
        uses: actions/setup-python@v4

      - name: Setup toolchain
        run: ./bootstrap

      - name: Build
        run: make

      - name: Move Generated files
        run: |
          mkdir -p artifacts
          mv draft-ietf-cellar-ebml-??.xml rfc8794.xml artifacts

      - name: XML Artifact
        uses: actions/upload-artifact@master
        with:
          name: ietf-xmls
          path: artifacts
